### ISSUE TITLE
update distributions?

### ISSUE THREAD

**Issue by isaak-pdm** [knassar702/awesome-linux-minimalism#5]
NixOS uses systemd. Maybe replace it with Alpine Linux (also I'm not sure if you can use nix without systemd, maybe Guix instead of Nix)?

**Comment by qume** [comment]
Came here to say the same thing. 

Love this repo concept but surprised to see alpine not top and center

**Comment by MindPatch** [comment]
Updated :+1: 
thank you for informing me this!
